[tool.poetry]
name = "python_base_package"
version = "0.1.0"
description = "Python template with some awesome tools to quickstart any Python project."
authors = ["Eric Lopes <nullhack@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "7.1.1"
pytest-cov = "^3.0.0"
pre-commit = "^2.18.1"
flake8 = "^4.0.1"
mypy = "^0.942"
isort = "^5.10.1"
black = {version = "^22.3.0", allow-prereleases = true}
flake8-docstrings = "^1.6.0"
xdoctest = "^1.0.0"
Pygments = "^2.11.2"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
pytest-html = "^3.1.1"
pdoc3 = "^0.10.0"
cookiecutter = "^1.7.3"
pylint = "^2.13.4"
graphviz = "^0.19.1"
pydot = "^1.4.2"
flake8-secure-coding-standard = "^1.2.1"
nox = "^2022.1.7"
flake8-todos = "^0.1.5"
flake8-logging-format = "^0.6.0"
flake8-builtins = "^1.5.3"
flake8-pytest-style = "^1.6.0"
lxml = "^4.8.0"
flake8-bugbear = "^22.3.23"
flake8-bandit = "^3.0.0"
flake8-annotations = "^2.8.0"
flake8-black = "^0.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --color=yes --cov=src --cov-fail-under=100 --cov-report term-missing --doctest-modules --cov-config=pyproject.toml"
testpaths = [
    "tests",
    "src"
]
python_files = ["*_test.py"]
python_functions = ["test_*"]
render_collapsed = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:"
    ]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
disallow_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_unused_ignores = true
show_error_context = true
error_summary = true
pretty = true
